In [1]:
#import pandas

# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# names=['sepal-length','sepal-width','petal-length','petal-width','class']
# dataset = pandas.read_csv(url,names=names)

#dataset.head(10)

from sklearn import datasets
from sklearn.neighbors import KNeighborsRegressor

#reading the iris dataset from the datasets package

iris = datasets.load_iris()

iris.data.shape,iris.target.shape

#implementing the methods of Logistic Regression 
m=KNeighborsRegressor()

# model = LogisticRegression()
# model.fit(iris.data,iris.target)
print(iris.target,iris.target_names,iris.feature_names,iris.DESCR)

# model.predict(iris.data)
#print(iris.target)



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] ['setosa' 'versicolor' 'virginica'] ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mea

In [2]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [3]:

#fit - fit the model according to the given training data
m.fit(iris.data,iris.target)


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [10]:
m.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [6]:
#kneighbors - returns indices and distances to the neighbors of each point.
m.kneighbors(iris.data,n_neighbors=2,return_distance=True)

(array([[ 0.        ,  0.1       ],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.33166248],
        [ 0.        ,  0.2236068 ],
        [ 0.        ,  0.1       ],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.1       ],
        [ 0.        ,  0.2236068 ],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.24494897],
        [ 0.        ,  0.41231056],
        [ 0.        ,  0.36055513],
        [ 0.        ,  0.34641016],
        [ 0.        ,  0.1       ],
        [ 0.        ,  0.33166248],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.28284271],
        [ 0.        ,  0.14142136],
        [ 0.        ,  0.45825757],
        [ 0.        ,  0.2       ],
        [ 0.        ,  0.3       ],
        [ 0.        ,  0.2       ],
        [ 0.        ,  0.2       ],
        [ 0.        ,  0.141

In [7]:
m.kneighbors_graph(iris.data,n_neighbors=2,mode='connectivity')

<150x150 sparse matrix of type '<class 'numpy.float64'>'
	with 300 stored elements in Compressed Sparse Row format>

In [8]:

m.predict(iris.data)

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  1. ,  1. ,  1. ,  1. ,
        1. ,  1.2,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
        1. ,  1. ,  1.2,  1. ,  1.6,  1. ,  1.6,  1. ,  1. ,  1. ,  1. ,
        1.4,  1. ,  1. ,  1. ,  1. ,  1. ,  1.8,  1. ,  1. ,  1. ,  1. ,
        1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,
        1. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  1.2,  2. ,  2. ,  2. ,
        1.8,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  2. ,  1.4,  2. ,
        2. ,  2. ,  1.8,  2. ,  2. ,  2. ,  1.8,  2. ,  2. ,  2. ,  2. ,
        2. ,  1.6,  1.8,  2. ,  2. ,  2. ,  1.8,  2. ,  2. ,  2. ,  2. ,
        2. ,  2. ,  2. ,  1.8,  2. ,  2. ,  2. ])

In [9]:
m.score(iris.data,iris.target)

0.96999999999999997

In [8]:
#m.sparsify()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)