In [83]:
#import pandas
import numpy as np

from sklearn.preprocessing import StandardScaler

# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# names=['sepal-length','sepal-width','petal-length','petal-width','class']
# dataset = pandas.read_csv(url,names=names)

#dataset.head(10)
zoo = r'C:\Users\priyu\Machine-Learning\zoo-animal-classification\zoo.csv'
#zoo_class = r'C:\Users\priyu\Machine-Learning\zoo-animal-classification\class.csv'
training_set = pandas.read_csv(zoo,index_col = False)
#zoo_class_set = pandas.read_csv(zoo_class, index_col = False)
zoo_data_df = training_set[['hair','feathers','eggs','milk','airborne','aquatic','predator','toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize']]
zoo_target_df = training_set[['class_type']]
zoo_target = zoo_target_df.values.ravel()
zoo_data = zoo_data_df.values.ravel()
zoo_data = np.array(zoo_data).reshape((len(zoo_data), 1))
zoo_data = scaler.transform(zoo_data)

#zoo_data = zoo_data.ravel()

print(zoo_data)
#print(zoo_class_set.head(5))

from sklearn import datasets
from sklearn.linear_model import LogisticRegression

#reading the iris dataset from the datasets package

iris = datasets.load_iris()

#print(iris.data.shape,iris.target.shape)

#implementing the methods of Logistic Regression 
m=LogisticRegression()

#model = LogisticRegression()
m.fit(zoo_data,zoo_target)
#print(iris.target,iris.target_names,iris.feature_names,iris.DESCR)

# model.predict(iris.data)
#print(iris.target)



NameError: name 'scaler' is not defined

In [59]:
#decision_function - to predict confidence scores (signed distance of that sample to the hyperplane) for examples.
m.decision_function(zoo_data)

array([[  3.52906187,  -5.19639759,  -4.10022657,  -7.57276213,
         -3.25314461,  -3.94475433,  -4.12258643],
       [  3.65807917,  -4.44918091,  -3.74851715,  -6.69493065,
         -4.24528791,  -4.10430859,  -5.60343024],
       [ -3.24999877,  -3.0461478 ,  -2.3959448 ,   1.70226423,
         -2.7628028 ,  -6.70606849,  -2.9730526 ],
       [  3.52906187,  -5.19639759,  -4.10022657,  -7.57276213,
         -3.25314461,  -3.94475433,  -4.12258643],
       [  3.46684868,  -4.67804395,  -3.66700067,  -7.25329172,
         -4.55903155,  -5.24524421,  -4.92245113],
       [  3.65807917,  -4.44918091,  -3.74851715,  -6.69493065,
         -4.24528791,  -4.10430859,  -5.60343024],
       [  3.72434103,  -4.40455426,  -4.07463453,  -6.6651427 ,
         -4.55841724,  -4.24384257,  -5.79315   ],
       [ -2.99250642,  -2.77265812,  -2.80357866,   2.29041325,
         -2.76218849,  -5.70466684,  -3.84375146],
       [ -3.24999877,  -3.0461478 ,  -2.3959448 ,   1.70226423,
         -2.7628

In [60]:
m.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'ovr',
 'n_jobs': 1,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [61]:

#fit_transform
m.fit_transform(zoo_data,zoo_target)

C:\Users\priyu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\priyu\Anaconda3\lib\site-packages\sklearn\utils\__init__.py:93: DeprecationWarning: Function transform is deprecated; Support to use estimators as feature selectors will be removed in version 0.19. Use SelectFromModel instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[1, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 1,

In [62]:

#predict - in the output below, 0-Setosa, 1-Versicolour, 2-Virginica
m.predict(zoo_data)

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2, 1,
       2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2, 1, 1,
       7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2, 6, 5, 2, 3,
       4, 1, 1, 2, 1, 6, 1, 7, 2], dtype=int64)

In [63]:
#predict_proba
m.predict_proba(zoo_data)

array([[  9.11380573e-01,   5.16524341e-03,   1.52901876e-02,
          4.82195693e-04,   3.49110095e-02,   1.78133052e-02,
          1.49574857e-02],
       [  9.33154235e-01,   1.10587776e-02,   2.20261199e-02,
          1.18276945e-03,   1.35245688e-02,   1.55389596e-02,
          3.51456959e-03],
       [  3.32898238e-02,   4.04755445e-02,   7.44533747e-02,
          7.54349151e-01,   5.29467252e-02,   1.08980713e-03,
          4.33955740e-02],
       [  9.11380573e-01,   5.16524341e-03,   1.52901876e-02,
          4.82195693e-04,   3.49110095e-02,   1.78133052e-02,
          1.49574857e-02],
       [  9.43865825e-01,   8.96585795e-03,   2.42517634e-02,
          6.88474271e-04,   1.00872544e-02,   5.10499300e-03,
          7.03583210e-03],
       [  9.33154235e-01,   1.10587776e-02,   2.20261199e-02,
          1.18276945e-03,   1.35245688e-02,   1.55389596e-02,
          3.51456959e-03],
       [  9.44278251e-01,   1.16763057e-02,   1.61637854e-02,
          1.23102470e-03,   1.00

In [64]:
m.predict_log_proba(zoo_data)

array([[ -0.09279472,  -5.26580305,  -4.18054399,  -7.63716052,
         -3.35495304,  -4.02780962,  -4.20254339],
       [ -0.06918478,  -4.50453081,  -3.81552626,  -6.7398966 ,
         -4.30324733,  -4.16440489,  -5.65083821],
       [ -3.40250352,  -3.20705733,  -2.59758219,  -0.28189995,
         -2.93846906,  -6.82175454,  -3.13739782],
       [ -0.09279472,  -5.26580305,  -4.18054399,  -7.63716052,
         -3.35495304,  -4.02780962,  -4.20254339],
       [ -0.05777126,  -4.71433148,  -3.71926595,  -7.28103261,
         -4.59648259,  -5.2775362 ,  -4.95673932],
       [ -0.06918478,  -4.50453081,  -3.81552626,  -6.7398966 ,
         -4.30324733,  -4.16440489,  -5.65083821],
       [ -0.0573344 ,  -4.45019364,  -4.12498201,  -6.69990837,
         -4.60233326,  -4.29158479,  -5.82968563],
       [ -3.18596784,  -2.97779606,  -3.00692409,  -0.24094026,
         -2.9679453 ,  -5.8525091 ,  -4.00945595],
       [ -3.40250352,  -3.20705733,  -2.59758219,  -0.28189995,
         -2.9384

In [65]:
m.score(zoo_data,zoo_target)

0.99009900990099009

In [66]:
m.sparsify()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)